// ╔══════════════════════════════════════════════════════════════╗
// ║  DEMO DATA - Cadence                                         ║
// ║  Ce fichier contient uniquement les données de démonstration ║
// ║  Séparé de la logique applicative (cadence.html)             ║
// ╚══════════════════════════════════════════════════════════════╝

function _mkC(g,w,t){return{givens:[g],whens:[w],thens:[t]};}

const DEMO_DATA={
  sprints:[
    // ─── Sprint 1 - FOUNDATION (clôturé) ───────────────────────────
    {id:'s1',number:1,label:'FOUNDATION',maxCap:100,closed:false,items:[
      {id:'i1',key:'BUG-001',type:'story',client:'bug-urgent',sp:15,status:'done',priority:1,
       assignees:['m2','m5'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'must'},
       desc:'15 bugs urgents en production (bloquants)',
       us:{role:'équipe de développement',want:'corriger les 15 bugs urgents identifiés en production',goal:'rétablir la stabilité de la plateforme pour tous les utilisateurs'},
       criteria:[_mkC('qu\'un bug urgent est identifié en production','le correctif est déployé','le bug n\'est plus reproductible et aucune régression n\'est constatée'),_mkC('que tous les bugs urgents sont corrigés','le sprint est livré','le taux d\'erreur en production revient à son niveau nominal')],
       notes:[{id:'n01',text:'Correction déployée le 16/06. Zéro régression. Monitoring actif 48h.',createdAt:'2026-06-16T09:30:00.000Z'}],
       dodChecks:{dor:[true, true, true, true, true],dod:[true, true, true, true, true]}},
      {id:'i2',key:'FAX-002',type:'epic',client:'faxfa',sp:30,status:'done',priority:1,
       assignees:['m1','m6'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'wsjf',wsjf:{businessValue:8,timeCriticality:6,riskReduction:3,jobSize:5},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:null},
       desc:'EPIC Carte interactive – partenaire le plus proche',
       us:{role:'assuré FAXFA',want:'visualiser les partenaires sur une carte interactive',goal:'choisir rapidement le professionnel le plus proche adapté à mon sinistre'},
       criteria:[_mkC('que je suis connecté et que j\'ai déclaré un sinistre','j\'accède à la carte interactive','les partenaires dans un rayon de 50 km s\'affichent avec leur nom, type et distance'),{givens:['que je clique sur un partenaire'],whens:['la fiche détail s\'ouvre'],thens:['je vois ses disponibilités et sa note','il m\'est proposé de l\'assigner directement au dossier']}],
       notes:[{id:'n02',text:'Intégration API Google Maps validée. Rayon configurable (défaut 50 km). Démo stakeholders OK.',createdAt:'2026-06-17T14:00:00.000Z'}],
       dodChecks:{dor:[true, true, true, true, true],dod:[true, true, true, true, true]}},
      {id:'i3',key:'MAN-003',type:'epic',client:'manfife',sp:20,status:'done',priority:1,
       assignees:['m3','m4'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'wsjf',wsjf:{businessValue:7,timeCriticality:5,riskReduction:8,jobSize:6},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:null},
       desc:'EPIC App mobile mode déconnecté',
       us:{role:'expert automobile sur site',want:'utiliser l\'application mobile sans connexion internet',goal:'remplir le formulaire d\'expertise même dans les casses automobiles sans réseau'},
       criteria:[_mkC('que je n\'ai pas de connexion internet','j\'ouvre l\'application mobile','toutes les fonctionnalités de saisie du formulaire d\'expertise sont accessibles'),_mkC('que j\'ai rempli un formulaire hors-ligne','mon appareil retrouve une connexion','les données sont synchronisées automatiquement avec le serveur')],
       notes:[],
       dodChecks:{dor:[true, true, true, true, true],dod:[true, true, true, true, true]}},
      {id:'i4',key:'AGA-004',type:'epic',client:'aganor',sp:10,status:'doing',priority:1,
       assignees:['m2'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'must'},
       desc:'EPIC Nouveau contrat + rétro-commission',
       us:{role:'gestionnaire AGANOR',want:'créer et gérer un nouveau type de contrat avec plafond 1 M€ et calcul rétro-commission',goal:'intégrer ce nouveau produit dans le logiciel et automatiser les calculs'},
       criteria:[_mkC('qu\'un sinistre est créé avec ce contrat','le montant dépasse 1 000 000 €','le remboursement est automatiquement plafonné'),_mkC('qu\'un apporteur d\'affaires est associé','le dossier est clôturé','la rétro-commission est calculée et une notification est envoyée')],
       notes:[{id:'n04',text:'Formule rétro-commission validée avec AGANOR. Reste : notification email + recette.',createdAt:'2026-06-18T10:15:00.000Z'}],
       dodChecks:{dor:[true, true, true, true, true],dod:[true, true, false, false, false]}},
      {id:'i5',key:'PME-005',type:'story',client:'pme',sp:25,status:'doing',priority:1,
       assignees:['m7','m8','m9'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'rice',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:500,impact:2,confidence:80,effort:3},moscow:null},
       desc:'Formulaire contact + bug bloquant + évol mobile + e-commerce 1/4 + site 1/4',
       us:{role:'PME cliente',want:'bénéficier d\'un formulaire de contact fonctionnel et de la correction du bug bloquant',goal:'assurer la continuité de mon activité en ligne'},
       criteria:[_mkC('qu\'un visiteur remplit le formulaire de contact','il clique sur Envoyer','un email est transmis au responsable et un message de confirmation s\'affiche')],
       notes:[{id:'n05a',text:'Formulaire contact livré. Bug bloquant corrigé. E-commerce 1/4 en cours.',createdAt:'2026-06-19T16:45:00.000Z'},{id:'n05b',text:'PME demande un délai sur e-commerce - livraison repoussée de 2 jours.',createdAt:'2026-06-20T09:00:00.000Z'}],
       dodChecks:{dor:[true, true, true, true, true],dod:[true, false, false, false, false]}},
    ]},
    // ─── Sprint 2 - MODERNISATION (actif) ──────────────────────────
    {id:'s2',number:2,label:'MODERNISATION',maxCap:100,closed:false,items:[
      {id:'i6',key:'BUG-006',type:'story',client:'bug-medium',sp:15,status:'todo',priority:2,
       assignees:['m2','m5'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'Bugs moyennement urgents – lot 1/2',
       us:{role:'équipe de développement',want:'corriger le premier lot de bugs moyennement urgents',goal:'réduire la dette technique et améliorer la stabilité'},
       criteria:[_mkC('qu\'un bug du lot 1 est sélectionné','le correctif est développé et testé','le bug est résolu sans régression sur les fonctionnalités adjacentes')],
       notes:[],
       dodChecks:{dor:[true, true, true, true, true],dod:[false, false, false, false, false]}},
      {id:'i7',key:'FAX-007',type:'epic',client:'faxfa',sp:30,status:'todo',priority:2,
       assignees:['m1','m3'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'wsjf',wsjf:{businessValue:9,timeCriticality:4,riskReduction:5,jobSize:8},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:null},
       desc:'EPIC IA Prédiction accidents & CA',
       us:{role:'directeur FAXFA',want:'accéder à des prédictions IA du nombre d\'accidents et du CA pour l\'année suivante',goal:'anticiper les besoins et optimiser la stratégie commerciale'},
       criteria:[{givens:['que les données historiques des 3 dernières années sont disponibles'],whens:['je lance le module de prédiction'],thens:['une estimation du nombre d\'accidents est générée','le CA prévisionnel N+1 est affiché avec un intervalle de confiance']}],
       notes:[{id:'n07',text:'Données historiques dispo depuis 2023. Modèle ML en évaluation : régression vs LSTM.',createdAt:'2026-06-21T11:00:00.000Z'}],
       dodChecks:{dor:[true, true, true, false, false],dod:[false, false, false, false, false]}},
      {id:'i8',key:'MAN-008',type:'epic',client:'manfife',sp:20,status:'todo',priority:2,
       assignees:['m4'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'must'},
       desc:'EPIC Remboursement COVID adhérents',
       us:{role:'adhérent MANFIFE',want:'recevoir automatiquement un remboursement de 30 € suite à la baisse des sinistres COVID',goal:'bénéficier de la redistribution sans démarche administrative'},
       criteria:[_mkC('que je suis un adhérent éligible','la campagne de remboursement est lancée','je reçois une notification et le versement de 30 € est initié sur mon IBAN'),_mkC('que mon IBAN n\'est pas renseigné','la campagne tente de me rembourser','je reçois un email me demandant de renseigner mon IBAN avant une date limite')],
       notes:[],
       dodChecks:{dor:[true, true, true, true, true],dod:[false, false, false, false, false]}},
      {id:'i9',key:'AGA-009',type:'epic',client:'aganor',sp:10,status:'todo',priority:2,
       assignees:['m2'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'must'},
       desc:'EPIC Norme IFRS 18 états financiers',
       us:{role:'responsable comptable AGANOR',want:'générer les états financiers conformes à la norme IFRS 18',goal:'satisfaire aux obligations réglementaires sans retraitement manuel'},
       criteria:[_mkC('que la période comptable est clôturée','je génère le rapport IFRS 18','le document est produit au format requis avec toutes les rubriques complétées')],
       notes:[{id:'n09',text:'Deadline réglementaire : applicable au 01/01/2027. Contrainte ferme.',createdAt:'2026-06-15T08:30:00.000Z'}],
       dodChecks:{dor:[true, true, true, true, true],dod:[false, false, false, false, false]}},
      {id:'i10',key:'SOC-010',type:'story',client:'socle',sp:15,status:'todo',priority:2,
       assignees:['m5','m10'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'must'},
       desc:'3 bugs urgents socle + réglementaire code assurance',
       us:{role:'Product Owner',want:'corriger les 3 bugs urgents du socle et intégrer la modification réglementaire',goal:'maintenir la conformité légale et la stabilité pour tous les clients'},
       criteria:[_mkC('que la modification du code des assurances est applicable','un nouveau dossier est créé','les nouvelles règles de calcul s\'appliquent automatiquement')],
       notes:[],
       dodChecks:{dor:[true, true, true, false, false],dod:[false, false, false, false, false]}},
      {id:'i11',key:'PME-011',type:'story',client:'pme',sp:10,status:'todo',priority:2,
       assignees:['m7','m9'],deps:['PME-005'],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'rice',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:500,impact:2,confidence:70,effort:2},moscow:null},
       desc:'Bug important + bug non bloquant + évol mobile + e-commerce 2/3 + site 2/4',
       us:{role:'PME cliente',want:'voir les bugs corrigés et la deuxième partie de ma boutique développée',goal:'offrir une expérience d\'achat complète à mes clients'},
       criteria:[_mkC('que la partie 2 de la boutique est déployée','un client navigue sur le site','le panier et la page produits sont fonctionnels')],
       notes:[]},
    ]},
    // ─── Sprint 3 - INTELLIGENCE ────────────────────────────────────
    {id:'s3',number:3,label:'INTELLIGENCE',maxCap:100,closed:false,items:[
      {id:'i12',key:'BUG-012',type:'story',client:'bug-medium',sp:15,status:'todo',priority:3,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'Bugs moyennement urgents – lot 2/2',
       us:{role:'équipe de développement',want:'corriger le second lot de bugs moyennement urgents',goal:'finaliser la résolution des anomalies et stabiliser la base de code'},
       criteria:[_mkC('que tous les bugs du lot 2 sont développés','la recette est effectuée','aucun bug du lot n\'est reproductible en production')],
       notes:[]},
      {id:'i13',key:'FAX-013',type:'epic',client:'faxfa',sp:30,status:'todo',priority:3,
       assignees:['m1','m3','m6'],deps:[],epicId:null,epicSp:null,deadline:{date:'2026-06-30',type:'imposed'},
       scoring:{framework:'wsjf',wsjf:{businessValue:10,timeCriticality:9,riskReduction:4,jobSize:7},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:null},
       desc:'EPIC Nouvelle version 3 React.js',
       us:{role:'utilisateur FAXFA',want:'bénéficier de la nouvelle version 3 refondée en React.js',goal:'profiter d\'une interface plus rapide, plus moderne et plus ergonomique'},
       criteria:[_mkC('que la version 3 est déployée','je me connecte','l\'interface se charge en moins de 2 secondes et toutes mes fonctionnalités sont disponibles')],
       notes:[{id:'n13',text:'Deadline imposée : 30/06/2026. Architecture React.js validée en atelier du 10/06. Risque : migration des composants legacy.',createdAt:'2026-06-10T14:00:00.000Z'}],
       dodChecks:{dor:[true, true, true, false, false],dod:[false, false, false, false, false]}},
      {id:'i14',key:'MAN-014',type:'epic',client:'manfife',sp:20,status:'todo',priority:3,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'must'},
       desc:'EPIC Portage v3 MANFIFE',
       us:{role:'utilisateur MANFIFE',want:'retrouver toutes les spécificités MANFIFE dans la version 3',goal:'conserver mes flux de travail dans la nouvelle architecture'},
       criteria:[_mkC('que le portage v3 MANFIFE est déployé','j\'utilise une fonctionnalité spécifique','le comportement est identique à la version précédente et les données sont préservées')],
       notes:[]},
      {id:'i15',key:'AGA-015',type:'epic',client:'aganor',sp:10,status:'todo',priority:3,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'must'},
       desc:'EPIC Portage v3 AGANOR',
       us:{role:'utilisateur AGANOR',want:'retrouver toutes les spécificités AGANOR dans la version 3',goal:'bénéficier de la nouvelle architecture sans perte de fonctionnalité'},
       criteria:[_mkC('que le portage v3 AGANOR est déployé','je réalise mes opérations courantes','les résultats sont identiques à ceux de la version précédente')],
       notes:[]},
      {id:'i16',key:'SOC-016',type:'story',client:'socle',sp:15,status:'todo',priority:3,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'3 bugs moyennement urgents socle',
       us:{role:'Product Owner',want:'corriger les 3 bugs moyennement urgents du socle commun',goal:'améliorer la qualité globale pour l\'ensemble des clients'},
       criteria:[_mkC('que les 3 bugs sont corrigés et testés','les tests de régression sont exécutés','aucun nouveau bug n\'est introduit')],
       notes:[]},
      {id:'i17',key:'PME-017',type:'story',client:'pme',sp:10,status:'todo',priority:3,
       assignees:['m7','m8'],deps:['PME-011'],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'Bug mineur ×2 + évol mobile + e-commerce 3/3 + site 3/4',
       us:{role:'PME cliente',want:'finaliser ma boutique e-commerce et continuer les évolutions de mon site',goal:'disposer d\'une boutique entièrement fonctionnelle'},
       criteria:[_mkC('que la partie 3 de la boutique est déployée','un client passe une commande','le paiement est traité et une confirmation est envoyée par email')],
       notes:[]},
    ]},
    // ─── Sprint 4 - EXCELLENCE ──────────────────────────────────────
    {id:'s4',number:4,label:'EXCELLENCE',maxCap:100,closed:false,items:[
      {id:'i18',key:'BUG-018',type:'story',client:'bug-minor',sp:15,status:'todo',priority:4,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'could'},
       desc:'Bugs mineurs – quand l\'équipe a du temps',
       us:{role:'équipe de développement',want:'traiter les bugs mineurs lors des disponibilités',goal:'réduire la dette technique sans impacter les livraisons prioritaires'},
       criteria:[_mkC('que l\'équipe dispose de temps dans le sprint','un bug mineur est sélectionné','il est traité, testé et intégré dans la release')],
       notes:[]},
      {id:'i19',key:'FAX-019',type:'story',client:'faxfa',sp:30,status:'todo',priority:4,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'15 bugs en souffrance FAXFA (1–5 SP)',
       us:{role:'utilisateur FAXFA',want:'voir les anomalies signalées depuis plus d\'un an enfin corrigées',goal:'utiliser le logiciel sans les irritants qui nuisent à la vélocité'},
       criteria:[_mkC('qu\'un bug en souffrance est sélectionné','le correctif est livré','le bug n\'est plus reproductible et le ticket est clôturé')],
       notes:[]},
      {id:'i20',key:'MAN-020',type:'story',client:'manfife',sp:20,status:'todo',priority:4,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'20 bugs en souffrance MANFIFE (2 SP chacun)',
       us:{role:'utilisateur MANFIFE',want:'voir les 20 anomalies signalées depuis 6 mois corrigées',goal:'retrouver un outil fiable et limiter les contournements manuels'},
       criteria:[_mkC('que les 20 bugs MANFIFE sont corrigés','la recette est validée','les tickets sont clôturés et l\'équipe MANFIFE confirme la résolution')],
       notes:[]},
      {id:'i21',key:'AGA-021',type:'story',client:'aganor',sp:10,status:'todo',priority:4,
       assignees:[],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'10 bugs en souffrance AGANOR (1 SP chacun)',
       us:{role:'utilisateur AGANOR',want:'voir les 10 anomalies signalées depuis 1 an et demi corrigées',goal:'éliminer les erreurs récurrentes qui génèrent des tickets de support'},
       criteria:[_mkC('que les 10 bugs AGANOR sont corrigés','les tests sont validés','le volume de tickets de support liés à ces bugs diminue de 100 %')],
       notes:[]},
      {id:'i22',key:'SOC-022',type:'story',client:'socle',sp:15,status:'todo',priority:4,
       assignees:['m2','m10'],deps:[],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'wsjf',wsjf:{businessValue:6,timeCriticality:3,riskReduction:7,jobSize:4},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:null},
       desc:'Optimisation base de données',
       us:{role:'Product Owner',want:'optimiser la base de données du socle commun',goal:'améliorer les performances globales et réduire les temps de réponse'},
       criteria:[{givens:['que l\'optimisation BDD est déployée'],whens:['une recherche de dossier est effectuée'],thens:['le temps de réponse est inférieur à 500 ms pour 95 % des requêtes','aucune dégradation n\'est constatée lors des pics de charge']}],
       notes:[{id:'n22',text:'Index manquants identifiés sur 3 tables critiques. Gain estimé : -60% temps de réponse requêtes de recherche.',createdAt:'2026-06-22T10:00:00.000Z'}]},
      {id:'i23',key:'PME-023',type:'story',client:'pme',sp:10,status:'todo',priority:4,
       assignees:[],deps:['PME-017'],epicId:null,epicSp:null,deadline:{date:'',type:'none'},
       scoring:{framework:'moscow',wsjf:{businessValue:3,timeCriticality:3,riskReduction:3,jobSize:3},rice:{reach:100,impact:1,confidence:80,effort:1},moscow:'should'},
       desc:'Bug mineur ×2 + évol mobile + 5 bugs ×1 SP + site vitrine 4/4',
       us:{role:'PME cliente',want:'finaliser mon site vitrine et corriger les derniers bugs mineurs',goal:'disposer d\'un site complet et sans anomalie connue'},
       criteria:[_mkC('que la partie 4 du site est déployée','un visiteur accède au site','toutes les sections s\'affichent correctement sur mobile, tablette et desktop')],
       notes:[]},
    ]},
  ],

  unassigned:[],

  team:[
    {id:'m1', name:'Aldo Raines',      role:'Dev Full-Stack', spDay:1, photo:''},
    {id:'m2', name:'Brienne de Torth', role:'Dev Back-End',   spDay:1, photo:''},
    {id:'m3', name:'Ellen Ripley',     role:'Dev Full-Stack', spDay:1, photo:''},
    {id:'m4', name:'Ellie Williams',   role:'Dev Back-End',   spDay:1, photo:''},
    {id:'m5', name:'Henry Jones Jr',   role:'Dev Back-End',   spDay:1, photo:''},
    {id:'m6', name:'Hugo Stiglitz',    role:'Dev Front-End',  spDay:1, photo:''},
    {id:'m7', name:'June Osbourne',    role:'Dev Front-End',  spDay:1, photo:''},
    {id:'m8', name:'Miles Morales',    role:'Dev Front-End',  spDay:1, photo:''},
    {id:'m9', name:'Selina Kyle',      role:'Dev Front-End',  spDay:1, photo:''},
    {id:'m10',name:'Snake Plissken',   role:'Dev Back-End',   spDay:1, photo:''},
  ],

  absences:[
    {id:'a1',memberId:'m6',title:'Congés Payés Hugo',type:'Congés payés',start:'2026-06-15',end:'2026-06-28',status:'En cours', daysCount:10,spLost:10,sprintsAffected:['s1']},
    {id:'a2',memberId:'m3',title:'Absence Ellen',    type:'Urgence',     start:'2026-06-17',end:'2026-06-17',status:'Terminée',daysCount:1, spLost:1, sprintsAffected:['s1']},
    {id:'a3',memberId:'m4',title:'Formation Ellie',  type:'Formation',   start:'2026-07-07',end:'2026-07-09',status:'Planifiée',daysCount:3, spLost:3, sprintsAffected:['s2']},
  ],

  roadmap:[
    {id:'g1',sprintId:'s1',icon:'🏗️',color:'linear-gradient(135deg,#dc2626,#b91c1c)',
     name:'FOUNDATION',goal:'Satisfaction clients majeurs + stabilité',
     metrics:['3 clients majeurs satisfaits','0 bug critique en prod','Avancement PME : 25 %','Boutique eCommerce PME-005 terminée']},
    {id:'g2',sprintId:'s2',icon:'⚙️',color:'linear-gradient(135deg,#1d4ed8,#4f46e5)',
     name:'MODERNISATION',goal:'FAXFA V3 & fiabilité technique',
     metrics:['V3 FAXFA en bonne voie','NPS > 40','PME 50 %','App Mobile MANFIFE terminée']},
    {id:'g3',sprintId:'s3',icon:'🤖',color:'linear-gradient(135deg,#7c3aed,#6d28d9)',
     name:'INTELLIGENCE',goal:'Migration V3 complète & Valeur ajoutée IA',
     metrics:['100 % clients V3','Dispo 99,9 %','PME 75 %','IA prédiction déployée']},
    {id:'g4',sprintId:'s4',icon:'🏆',color:'linear-gradient(135deg,#15803d,#16a34a)',
     name:'EXCELLENCE',goal:'Excellence opérationnelle',
     metrics:['Dette tech -50 %','Perf +40 %','5 PME livrées','Site PME vitrine livré']},
  ],

  kanbanColumns:[
    {id:'todo',  name:'À faire',  color:'#6b7280'},
    {id:'doing', name:'En cours', color:'#d97706'},
    {id:'done',  name:'Terminé',  color:'#16a34a'},
  ],

  clients:[
    {id:'cl1',key:'faxfa',   label:'FAXFA',   color:'#1d4ed8',description:'Assureur automobile - 12 ans de partenariat'},
    {id:'cl2',key:'manfife', label:'MANFIFE',  color:'#15803d',description:'Mutuelle nationale - 8 ans de partenariat'},
    {id:'cl3',key:'aganor',  label:'AGANOR',  color:'#7c3aed',description:'Courtier régional - 5 ans de partenariat'},
    {id:'cl4',key:'socle',   label:'Socle',   color:'#475569',description:'Fonctionnalités transverses mutualisées'},
    {id:'cl5',key:'pme',     label:'PME',     color:'#c2410c',description:'Petites et moyennes entreprises - nouveau périmètre 2026'},
  ],

  settings:{
    projectName:      'Cadence',
    teamName:         'Équipe Dev',
    sprintDuration:   10,
    sprintUnit:       'days',
    startDate:        '2026-06-15',
    spPerPersonPerDay: 1,
    teamSize:         10,
    year:             2026,
    dor:[
      'User Story rédigée (rôle / besoin / objectif)',
      'Critères d\'acceptation définis (Gherkin)',
      'Estimé en SP par l\'équipe',
      'Dépendances identifiées et prises en compte',
      'Aucun bloqueur connu',
    ],
    dod:[
      'Code développé et en revue (code review)',
      'Tests unitaires écrits et passants',
      'Recette fonctionnelle validée par le PO',
      'Déployé en environnement de recette',
      'Documentation mise à jour',
    ],
  },

  nextItemId:    24,
  nextSprintId:  5,
  nextMemberId:  11,
  nextClientId:  6,
  nextRetroId:   3,

  retros:[
    // Rétro Sprint 1 - FOUNDATION (complète avec actions)
    {id:'ret1',sprintId:'s1',format:'ssc',createdAt:'2026-06-26T09:00:00.000Z',
     cards:[
       {id:'rc01',column:'start',text:'Faire une démo intermédiaire à mi-sprint pour les clients',votes:4,createdAt:'2026-06-26T09:10:00.000Z'},
       {id:'rc02',column:'start',text:'Documenter les décisions techniques en temps réel',votes:2,createdAt:'2026-06-26T09:11:00.000Z'},
       {id:'rc03',column:'stop',text:'Interrompre les devs pour des questions en dehors du daily',votes:5,createdAt:'2026-06-26T09:12:00.000Z'},
       {id:'rc04',column:'stop',text:'Sous-estimer les items liés à l\'intégration API tierce',votes:3,createdAt:'2026-06-26T09:13:00.000Z'},
       {id:'rc05',column:'continue',text:'Code review systématique avant merge',votes:6,createdAt:'2026-06-26T09:14:00.000Z'},
       {id:'rc06',column:'continue',text:'Daily à 9h30 - format et durée au top',votes:3,createdAt:'2026-06-26T09:15:00.000Z'},
       {id:'rc07',column:'continue',text:'Canal Slack #alerts pour les bugs urgents',votes:2,createdAt:'2026-06-26T09:16:00.000Z'},
     ],
     actions:[
       {id:'ra01',text:'Créer un template de démo intermédiaire (15 min max)',owner:'m1',deadline:'2026-07-03',status:'done',createdAt:'2026-06-26T09:30:00.000Z'},
       {id:'ra02',text:'Mettre en place un canal #no-interruption en dehors de 10h-12h et 14h-16h',owner:'m2',deadline:'2026-06-30',status:'done',createdAt:'2026-06-26T09:31:00.000Z'},
       {id:'ra03',text:'Ajouter une checklist API tierce dans la DoR pour les items d\'intégration',owner:'m1',deadline:'2026-07-07',status:'todo',createdAt:'2026-06-26T09:32:00.000Z'},
     ]},
    // Rétro Sprint 2 - MODERNISATION (en cours de remplissage)
    {id:'ret2',sprintId:'s2',format:'ssc',createdAt:'2026-07-10T09:00:00.000Z',
     cards:[
       {id:'rc11',column:'start',text:'Inclure les estimations de complexité IA dans le planning Sprint 3',votes:3,createdAt:'2026-07-10T09:10:00.000Z'},
       {id:'rc12',column:'stop',text:'Livrer des épics partiellement sans valider avec le client',votes:4,createdAt:'2026-07-10T09:11:00.000Z'},
       {id:'rc13',column:'continue',text:'Pair programming sur les sujets IA / ML - bonne montée en compétence',votes:5,createdAt:'2026-07-10T09:12:00.000Z'},
     ],
     actions:[
       {id:'ra11',text:'Atelier estimation IA avec toute l\'équipe avant Sprint 3',owner:'m3',deadline:'2026-07-14',status:'todo',createdAt:'2026-07-10T09:30:00.000Z'},
     ]},
  ],
};
